In [1]:
import numpy as np

creating

In [2]:
x1 = np.array([1,2,3,4])
print(x1)
print(x1.shape)
print(x1.ndim)
print(type(x1))

[1 2 3 4]
(4,)
1
<class 'numpy.ndarray'>


In [4]:
a = np.arange(10,30, .5)
print(a)

[10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5 15.  15.5 16.  16.5
 17.  17.5 18.  18.5 19.  19.5 20.  20.5 21.  21.5 22.  22.5 23.  23.5
 24.  24.5 25.  25.5 26.  26.5 27.  27.5 28.  28.5 29.  29.5]


In [15]:
c = np.random.randint(-10,10,(5,5))
print(c)

[[-1  2  2 -1 -4]
 [-9 -3 -8  3  9]
 [-7 -1 -2 -6 -2]
 [-5  9  6  9 -7]
 [ 8 -2 -3 -8 -7]]
